[package]
name = "solid"
version = "0.0.1"
edition = "2021"

[features]
default = []
alloc = []
std = ["alloc"]

[dependencies]
autocxx = "0.22.0"
cxx = "1.0"
macropol = "0.1.3"
paste = "1.0.8"

[build-dependencies]
autocxx-build = "0.22.0"
miette = { version = "4.7", features = ["fancy"] }
